nginx:
    build: ./nginx
    ports:
      - "800:80"
    links:
      - "php"
    volumes:
      - ~/work:/opt

php:
    build: ./php
    ports:
      - "90000:9000"
    links:
      - "mysql"
      - "redis"
    volumes:
      - ~/work:/opt

mysql:
    build: ./mysql
    ports:
      - "33066:3306"
    volumes:
      - ~/work/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Apple1992

redis:
    build: ./redis
    ports:
      - "63799:6379"